# Site settings
name: Obai Anaya
title: Obai Anaya
description: Coding By Day, Filming By Dusk
url: https://obaianaya.github.io/
baseurl: ''
email: obai.anayeh@gmail.com
cover: https://obaianaya.github.io/img/og.png
logo: https://obaianaya.github.io/img/emojis/technologist.png
resume: https://obaianaya.github.io/resume.pdf
social:
  - title: email
    url: mailto:obai.anayeh@gmail.com
  - title: instagram
    url: https://instagram.com/obai.anaya
  - title: github
    url: https://github.com/obaianaya
  - title: linkedin
    url: https://www.linkedin.com/in/obaianaya

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
